# Generated by Django 4.1.5 on 2023-01-28 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_alter_student_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthDay',
            field=models.DateField(default=datetime.datetime(2023, 1, 28, 17, 31, 42, 496347), null=True),
        ),
    ]
