# Generated by Django 4.1.6 on 2023-02-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='st',
            field=models.CharField(choices=[('salom', 'salom')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
